defconfig: Comply with vintf requirements
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    For config CONFIG_ANDROID_PARANOID_NETWORK, value = y but required n
    Missing config CONFIG_CRYPTO_CHACHA20POLY1305
    Missing config CONFIG_TRACE_GPU_MEM
    Missing config CONFIG_XFRM_MIGRATE

Co-authored-by: CuriousNom <aryanbiswas7585@gmail.com>
Change-Id: Iac64fa1c9db540f24a2ada2b90309d01d51fc6e6